name: sticky_example
version: 0.1.0
environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.2.0
  sticky:
    path: ..
  sass_builder: ^2.1.2
  
dev_dependencies:
  build_runner: ^1.2.5
  build_web_compilers: ^1.1.0

dependency_overrides:
  analyzer: 0.35.0