name: sticky_example
version: 0.1.0
environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha
  sticky:
    path: ..
  sass_builder: ^2.1.3
  
dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers: ^2.1.0
