name: sticky_example
version: 0.1.0
environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  angular: ^5.0.0
  sticky:
    path: ..
  
dev_dependencies:   
  sass_builder: ^2.1.2
  build_runner: ^0.9.2
  build_web_compilers: ^0.4.1