name: sticky_example
version: 0.1.0
publish_to: none
environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  angular: ^7.0.0-alpha
  sass_builder: ^2.1.4
  sticky:
    path: ..

dev_dependencies:
  build_runner: ^2.1.2
  build_web_compilers: ^3.2.1
